### ISSUE TITLE
meaning of drep, drnn, demb

### ISSUE THREAD

**Issue by zhangj1an** [facebookresearch/RTFM#4]
hi, nice and creative work!

In RTFM/exp_utils.py, line 46-49, inside function get_parser(), what does the "drep", "drnn", "demb" variables represent respectively? Thanks!

**Comment by egrefen** [comment]
From memory, those are the vector sizes (dimensionality) for the output representations, the rnn hidden layers, and the input embeddings, respectively.

**Comment by zhangj1an** [comment]
This solves my problem. Thank you!
